export declare const bidChange: import("firebase-functions/v1").CloudFunction<import("firebase-functions/v1").Change<import("firebase-functions/v1/firestore").QueryDocumentSnapshot>>;
export declare const increaseRaisedMoney: import("firebase-functions/v1").CloudFunction<import("firebase-functions/v1").Change<import("firebase-functions/v1/firestore").QueryDocumentSnapshot>>;
export declare const endAuction: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const changeHandover: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const exportAuction: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const processAuctionImage: import("firebase-functions/v1").CloudFunction<import("firebase-functions/v1/storage").ObjectMetadata>;
export declare const handoverConfirm: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const sendWinnerMail: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const downloadMails: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const testSendWinnerMail: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
